import random
import tkinter as tk
root = tk.Tk()
Colors = ["red","orange","yellow","green","blue","purple"]
random_color = random.choice(Colors)
Button1 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button2 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button3 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button4 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button5 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button6 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button7 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button8 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button9 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)

Button10 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button11 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button12 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button13 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button14 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button15 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)
Button16 = tk.Button(root, text = random_color,bg = random_color,command=lambda c=random_color:print(c))
random_color = random.choice(Colors)

Button1.grid(row=0, column=0)
Button2.grid(row=0, column=1)
Button3.grid(row=0, column=2)
Button4.grid(row=0, column=3)
Button5.grid(row=1, column=0)
Button6.grid(row=2, column=0)
Button7.grid(row=3, column=0)
Button8.grid(row=1, column=1)
Button9.grid(row=2, column=1)
Button10.grid(row=3, column=1)
Button11.grid(row=1, column=2)
Button12.grid(row=1, column=3)
Button13.grid(row=2, column=2)
Button14.grid(row=2, column=3)
Button15.grid(row=3, column=3)
Button16.grid(row=3, column=2)
root.mainloop()
